from enum import Enum

class GameBoardSquareState(Enum):
        SNAKE_SELF_BODY = -11
        SNAKE_STRONGER_ENEMY_HEAD = -4
        SNAKE_EQUAL_ENEMY_HEAD = -3
        SNAKE_WEAKER_ENEMY_HEAD = -2
        SNAKE_SELF_HEAD = -1
        SNAKE_ENEMY_BODY = 0
        NULL = 0
        SNAKE_ENEMY_TAIL = 0
        HAZARD = 1
        BAD_LOOKAHEAD = 2
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE = 3
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE = 4
        EMPTY_CORNER = 5
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE_1_STEP = 6
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE_2_STEPS = 7
        POOR_LOOKAHEAD = 8
        SNAKE_SELF_TAIL_TARGET = 9
        EMPTY_CORNER_1_STEP = 10
        SNAKE_SELF_TAIL = 11
        SNAKE_SELF_BODY_1_STEP = 12
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE_1_STEP = 13
        EMPTY_CORNER_2_STEPS = 15
        SNAKE_ENEMY_BODY_1_STEP = 16
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE_3_STEPS = 17
        EMPTY_CORNER_3_STEPS = 19
        QUESTIONABLE_LOOKAHEAD = 22
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE_2_STEPS = 23
        AVOID_FOOD = 25
        SNAKE_ENEMY_BODY_2_STEPS = 26
        SNAKE_SELF_BODY_2_STEPS = 27
        EMPTY_EDGE = 30
        EMPTY_EDGE_1_STEP = 35
        EMPTY_EDGE_2_STEPS = 40
        EMPTY_EDGE_3_STEPS = 45
        EMPTY = 50
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE_3_STEPS = 53
        SNAKE_SELF_TAIL_TARGET_4_STEPS = 58
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_4_STEPS = 59
        FOOD_4_STEPS = 60
        SNAKE_SELF_TAIL_TARGET_3_STEPS = 68
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_3_STEPS = 69
        FOOD_3_STEPS = 70
        SNAKE_SELF_TAIL_TARGET_2_STEPS = 78
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_2_STEPS = 79
        FOOD_2_STEPS = 80
        SNAKE_SELF_TAIL_TARGET_1_STEP = 88
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_1_STEP = 89
        FOOD_1_STEP = 90
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE = 99
        FOOD = 100

        @classmethod
        def has_value(cls, value):
            return any(value == item.value for item in cls)

