from enum import Enum

class GameBoardSquareState(Enum):
        EMPTY = 50
        EMPTY_CORNER = 5
        EMPTY_CORNER_1_STEP = 10
        EMPTY_CORNER_2_STEPS = 15
        EMPTY_CORNER_3_STEPS = 19
        EMPTY_EDGE = 20
        EMPTY_EDGE_1_STEP = 30
        EMPTY_EDGE_2_STEPS = 40
        FOOD = 100
        AVOID_FOOD = 25
        FOOD_1_STEP = 90
        FOOD_2_STEPS = 80
        FOOD_3_STEPS = 70
        FOOD_4_STEPS = 60
        SNAKE_SELF_HEAD = -1
        SNAKE_SELF_BODY = -11
        SNAKE_SELF_TAIL = 47
        SNAKE_SELF_BODY_1_STEP = 11
        SNAKE_SELF_BODY_2_STEPS = 27
        SNAKE_ENEMY_BODY_1_STEP = 16
        SNAKE_ENEMY_BODY_2_STEPS = 26
        SNAKE_ENEMY_BODY = 0
        SNAKE_ENEMY_TAIL = 1
        SNAKE_STRONGER_ENEMY_HEAD = -4
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE = 4
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE_1_STEP = 6
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE_2_STEPS = 7
        SNAKE_STRONGER_ENEMY_HEAD_CAN_MOVE_3_STEPS = 18
        SNAKE_EQUAL_ENEMY_HEAD = -3
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE = 3
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE_1_STEP = 13
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE_2_STEPS = 23
        SNAKE_EQUAL_ENEMY_HEAD_CAN_MOVE_3_STEPS = 33
        SNAKE_WEAKER_ENEMY_HEAD = -2
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE = 99
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_1_STEP = 89
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_2_STEP = 79
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_3_STEP = 69
        SNAKE_WEAKER_ENEMY_HEAD_CAN_MOVE_4_STEP = 59
        HAZARD = -99
        HAZARD_1_STEP = 48
        NULL = 0
        
        @classmethod
        def has_value(cls, value):
            return any(value == item.value for item in cls)

